# Generated by Django 6.0.6 on 2026-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
